---
# yamllint disable-line rule:line-length
# From https://presstige.io/p/Using-GitHub-Actions-with-Go-2ca9744b531f4f21bdae9976d1ccbb58

name: Build and test Go
# Seriously? https://github.com/adrienverge/yamllint/issues/158
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ matrix.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-build-

      - name: Staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Review Linting
        run: |
          go get -u github.com/mgechev/revive
          make lint
  # https://github.community/t/trigger-job-on-tag-push-only/18076
  release:
    name: Release
    if: github.event_name = 'push' && contains(github.ref, '/tags/v')
    strategy:
      matrix:
        os: [ubuntu-latest]
    needs:
      - build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dummy
        run: |
          echo "Dummy Step: ${{ github.ref }}"
